### ISSUE TITLE
有关引用文献类型和公式字体的答疑

### ISSUE THREAD

**Issue by cuiao** [cuiao/SCU_ThesisDissertation_LaTeXTemplate#13]
@Yaping-Wang 在 https://github.com/cuiao/SCU_ThesisDissertation_LaTeXTemplate/commit/3856ee578f2fd200251fb588b3fc5a8d11b7f3ea 中提到：
>在使用过程中，我发现模板中给的参考文献格式中期刊文章的标志应该为J，但是显示的却是G，不知道是什么情况？另外，学校对数学公式的要求是字体使用Times New Roman，不知道LaTeX现在使用的公式字体是否可以？

**Comment by cuiao** [comment]
@Yaping-Wang，回答一下你的问题哈

1. 期刊文章的文献类型应在 .bib 文件中为 ARTICLE 类型，并需正确填写作者、标题、杂志、期号和页数等信息，会自动标记为 J，这个模版使用了东南大学的文献分类文件，是符合国标的，最近一次的提交中#12 我更新了[手册](https://github.com/cuiao/SCU_ThesisDissertation_LaTeXTemplate/blob/master/Manual/Manual.pdf)和其对应的[参考文献数据文件](https://github.com/cuiao/SCU_ThesisDissertation_LaTeXTemplate/blob/master/Manual/Manualbib.bib)，你可以参考一下；

2. 根据我的记忆学校只是对正文中的英文要求为 Times New Roman 字体，并没有针对数学公式作出明确要求，详细请参阅 [cuiao/SCU_ThesisDissertation_LaTeXTemplate/Reference Document/四川大学硕士、博士学位论文格式.doc](https://github.com/cuiao/SCU_ThesisDissertation_LaTeXTemplate/blob/master/Reference%20Document/%E5%9B%9B%E5%B7%9D%E5%A4%A7%E5%AD%A6%E7%A1%95%E5%A3%AB%E3%80%81%E5%8D%9A%E5%A3%AB%E5%AD%A6%E4%BD%8D%E8%AE%BA%E6%96%87%E6%A0%BC%E5%BC%8F.doc)；

最后，非常感谢你的使用，不过使用文档我还没有写完，这个主要是因为我比较懒，模版的使用过程中有任何的问题欢迎沟通哦~
:octocat:

**Comment by Yaping-Wang** [comment]
感谢学长的无私奉献！

**Comment by Yaping-Wang** [comment]
学长你好，我今天打开文件尝试编译了一下，发现几个问题：
1、当标题名称过长的时候不会自动换行，我尝试加入“\\”手动换行，但是无法渲染，再删掉“\\”之后也无法顺利渲染了（使用了xeLaTeX、xeTeX均不行）。
2、上一步渲染终止在\maketitle，如果把该行改为备注，渲染会终止在\begin{reference}。

**Comment by cuiao** [comment]
问题已在 Pull Request #15 中解决，请按照说明使用
😆
