### ISSUE TITLE
XelaTex编译报错

### ISSUE THREAD

**Issue by jacky2183** [cuiao/SCU_ThesisDissertation_LaTeXTemplate#16]
Cuiao 你好！

我是川大华西公共卫生学院的研究生，日前发现你制作了我校论文的latex模板，不过我在使用的时候发现一些问题，望你可以帮忙解答，谢谢！
问题如下：我下载了你最新的模板，使用XelaTex运行manual.tex，不过出现很多关于“Undefined control sequence”的报错，我查找了很多资料，却无法解决，希望能得到你的帮助。
如可以，我们可以用邮件交流，我的邮箱jacky2183@163.com，再次感谢。

**Comment by cuiao** [comment]
请使用 pdflatex 进行编译。
😃

**Comment by jacky2183** [comment]
好的，多谢，我试试，多谢帮忙，如有问题再向你咨询哈。

**Comment by cuiao** [comment]
No problem
😄

**Comment by jacky2183** [comment]
学长你好！


我是川大2015级博士生，目前正在使用你的latex模板写博士论文，有一个关于参考文献格式的问题，想请教你，就是目前的参考文献格式中都是作者名在前，姓在后，想问你一下如何调整为姓在前，名在后？


谢谢



------------------
Fei ChenDepartment of Medical StatisticsWest china school of public Health,Sichuan University
17#,Section 3,Renmin Nan Road
Chengdu, Sichuan 610041
Tel:86-15102815835




 





------------------ 原始邮件 ------------------
发件人: "Cui Ao";<notifications@github.com>;
发送时间: 2016年12月28日(星期三) 下午4:20
收件人: "cuiao/SCU_ThesisDissertation_LaTeXTemplate"<SCU_ThesisDissertation_LaTeXTemplate@noreply.github.com>; 
抄送: "陈飞"<674570061@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [cuiao/SCU_ThesisDissertation_LaTeXTemplate] XelaTex编译报错 (#16)




Closed #16.
