### ISSUE TITLE
macOS 环境下渲染字体出现问题

### ISSUE THREAD

**Issue by Yaping-Wang** [cuiao/SCU_ThesisDissertation_LaTeXTemplate#17]
学长你好，我在使用 MacTeX 对模板进行渲染时发现中英文摘要中的标题显示有误，我觉得应该是 macOS 的字体与 Windows 不同导致的，但是我不清楚应该怎么修改字体才能适配 macOS 系统，请指教！
<img width="679" alt="2017-02-12 09 58 58" src="https://cloud.githubusercontent.com/assets/23613683/22859024/fcfe7308-f109-11e6-86a8-2c61ae31f081.png">
<img width="670" alt="2017-02-12 09 59 13" src="https://cloud.githubusercontent.com/assets/23613683/22859025/fd1f0d34-f109-11e6-9675-8e5e62c6bf4f.png">
<img width="884" alt="2017-02-12 10 03 48" src="https://cloud.githubusercontent.com/assets/23613683/22859049/a331d67a-f10a-11e6-82c9-7e4556d9eda3.png">

**Comment by cuiao** [comment]
实在不好意思，我没有用过MAC OS，不能帮你测试，不过我估计是你系统中缺少相对应的中文字体，你可以试试在系统中安装黑体，或者在SCU_ThesisDissertation_LaTeXTemplate/Template/scuthesis.cls文件中修改heiti为别的字体名。

**Comment by Yaping-Wang** [comment]
好的，我去试一下。我看到目前知乎上关于 MacTeX 的中文化解决方案是使用 fontspec 包指定不同的字体，但是这个字体包一般是加在 tex 文件中，而模板是在 cls 文件中，我不知道具体该如何修改。请问是否可以将字体指派的代码提到一个较为明显的地方，这样就可以很方便的修改，或者将 macOS 下指定字体的代码写好加上%变为注释，使得大家使用模板的时候可以根据自己的系统方便的切换默认字体呢？

**Comment by leo-liu** [comment]
模板中根本就不存在字体定义的代码，因为字体定义是在 `ctex` 包中完成的。
而 `ctex` 是会自动判断操作系统并使用 Mac OS 附带的华文字体的。
从图片看，宋体、黑体、楷体显示也都是正常的。

这里也**根本不是中文字体的问题**。

看了你的代码，是没有正确使用数学模式，直接在正文模式就硬写数学公式（其实是化学公式）。TeX 在处理
```tex
\gamma -Al_2O_3
```
这种地方时就已经出错了，遑论其他？

先正经学习一下 LaTeX，看完一个基本的百来页的教程后再使用吧。

**Comment by cuiao** [comment]
化学方面怎么用 LaTeX 我的确也不太清楚，@leo-liu所提及的问题@Yaping-Wang可以参考一下，确实你直接使用 \gamma 是存在问题的，多谢@leo-liu的帮助。本模板在编写中的很多地方参考了@leo-liu所编著《LaTeX入门》一书，作为一个初学者的试手，这本书对我的帮助很大，在此一并感谢并推荐给@Yaping-Wang参考。

此外，每个人都有一个学习由浅入深的过程，而敢于尝试新的事物是需要鼓励和支持的。希望先知者对于后知者所犯的 Rookie Mistakes 多多包涵。

**Comment by leo-liu** [comment]
化学公式用 `mhchem` 包或者 `chemformula` 包。

**Comment by Yaping-Wang** [comment]
感谢 @leo-liu @cuiao 两位前辈的解答，这次是我犯了很肤浅的错误，谢谢指正，我现在正在努力学习 LaTeX，希望以后有问题还能多向两位前辈请教。感谢！
