### ISSUE TITLE
Mac OS 下模板编译无法通过

### ISSUE THREAD

**Issue by alwaysgoodtime** [cuiao/SCU_ThesisDissertation_LaTeXTemplate#18]
学长您好，我是川大的本科生，Mac系统的用户，下载您的毕业论文模板后直接打开，发现maketitle这一行首先就出现了问题，我用的是mactex，用其自带的texshop编辑器打开的，用的是xelatex编译，bug提示如下，
<img width="500" alt="2017-03-09 3 54 34" src="https://cloud.githubusercontent.com/assets/26213739/23741385/2e9d1b2a-04e3-11e7-8deb-162c13b268b4.png">

忽略问题强行通过编译后生成的pdf文件如下：
[MainBody.pdf](https://github.com/cuiao/SCU_ThesisDissertation_LaTeXTemplate/files/830146/MainBody.pdf)
过程中所有的编译提示命令如下：
[编译过程.docx](https://github.com/cuiao/SCU_ThesisDissertation_LaTeXTemplate/files/830167/default.docx)
请问最后输出的pdf文件是否改变了格式？我是否需要做一些设置和调整？如果需要的话， 应该怎么做呢？

**Comment by cuiao** [comment]
您好，由于模板文件中新加入了 _\CoverTitle{}_ 命令（封面标题），而 _MainBody.tex_ 文件中并未同步更新，才引起了以上问题。问题已在最新的代码中更正。Commit: https://github.com/cuiao/SCU_ThesisDissertation_LaTeXTemplate/commit/68109782bba2953fd2cd57353a462c85c364113b，谢谢。


此外，据我所知本科毕业论文的格式要求和硕、博士研究生的毕业论文格式要求不同，而本模板参考研究生毕业论文要求制作，建议本科同学慎用。
