### ISSUE TITLE
编译出错请教

### ISSUE THREAD

**Issue by LinzhangJiang** [cuiao/SCU_ThesisDissertation_LaTeXTemplate#19]
您好，很感谢您的模板，觉得很实用，但是在适应过程中发现这样一个问题不知如何解决，我使用pdfLatex编译得到的目录是红色字体，更严重的是目录中“第一章”三个字与后面紧跟着的标题”绪论“有重合，请问如何在这个模板中解决这个问题，谢谢！

**Comment by cuiao** [comment]
请贴出你的代码哈
