### ISSUE TITLE
参考文献格式问题

### ISSUE THREAD

**Issue by jacky2183** [cuiao/SCU_ThesisDissertation_LaTeXTemplate#20]
学长你好！

我是川大2015级博士生，目前正在使用你的latex模板写博士论文，有一个关于参考文献格式的问题，想请教你，就是目前的参考文献格式中都是作者名在前，姓在后，想问你一下如何调整为姓在前，名在后？

谢谢

**Comment by cuiao** [comment]
当前确实是姓在前名在后啊，比如Peter Wilson and Herries Press就为Wilson P. 和Press H.
如果你只是想把姓名颠倒的话，直接修改bib会比较简单。
