### ISSUE TITLE
每行字数的问题

### ISSUE THREAD

**Issue by marasilence** [cuiao/SCU_ThesisDissertation_LaTeXTemplate#21]
我看了下川大的模版要求，我看每行要求是34个汉字，而latex生成的每行是36个汉字。页边距也没啥问题啊，问题在哪呢

**Comment by liyang0282019** [comment]
修改页面16K, 每行34个字
修改文件：Template\scuthesis.cls
替换其中的papersize{27cm}{19.5cm} 为 \papersize{26cm}{18.4cm}
\RequirePackage{anysize}
%\papersize{27cm}{19.5cm}
\papersize{26cm}{18.4cm}
